# 設定ファイル
# 
# つぶやきにハッシュタグを加えるかどうか[true,false]
ENABLE_HASHTAG: false
# texファイルのパス
# Windowsで絶対パスを指定する場合は\(バックスラッシュ)の扱いに気をつけてください
TEX_FILE_PATH: "thesis.tex"
# texファイルのエンコーディング
TEX_FILE_ENCODING: "UTF-8"
# pdfファイルのパス
PDF_FILE_PATH: "thesis.pdf"
# Xクエスト（Xには"卒論", "修論", "博論"などを指定）
THESIS_NAME: "卒論"
# OAuth認証の設定
# 次の開発者向けページで新規アプリケーションを作成してください
# https://dev.twitter.com/
CONSUMER_KEY: ""
CONSUMER_SECRET: ""
ACCESS_TOKEN: ""
ACCESS_TOKEN_SECRET: ""
